[llvm]
ninja = true
targets = "X86"
experimental-targets = ""
link-shared = true

[build]
docs = false
extended = true
cargo = "/usr/bin/cargo"
rustc = "/usr/bin/rustc"
python = "python"
sanitizers = false

[install]
prefix = "/usr"

[rust]
channel = "stable"
rpath = false
codegen-tests = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
