[llvm]
targets = "X86"
link-shared = true

[build]
cargo = "/usr/bin/cargo"
rustc = "/usr/bin/rustc"
python = "python"
docs = false
extended = true
sanitizers = false

[install]
prefix = "/usr"

[rust]
channel = "stable"
rpath = false
codegen-tests = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
