#!/bin/bash
# This file based in part on the mkinitrafms script for the LFS LiveCD
# written by Alexander E. Patrakov and Jeremy Huntwork.

copy() {
    local file

    if [ "$2" == "lib" ]; then
        file=$(PATH=/lib:/usr/lib:/usr/lib/systemd type -p $1)
    else
        file=$(type -p $1)
    fi

    if [ -n $file ] ; then
        cp $file $WDIR/$2
    else
        echo "Missing required file: $1 for directory $2"
        rm -rf $WDIR
        exit 1
    fi
}

INITRAMFS_FILE=initrd-${1}

printf "Creating $INITRAMFS_FILE... "


libs=$(mktemp /tmp/libs.XXXXXXXXXX)

DATADIR=.
INITIN=init.in.${1}

# Create a temporrary working directory
WDIR=$(mktemp -d /tmp/initrd-work.XXXXXXXXXX)

# Create base directory structure
mkdir -p $WDIR/{bin,dev/mapper,lib/firmware,run,sbin,sys,proc,usr}
mkdir -p $WDIR/etc/{modprobe.d,udev/rules.d}
touch $WDIR/etc/modprobe.d/modprobe.conf
ln -s lib $WDIR/lib64
ln -s ../lib $WDIR/usr/lib
ln -s ../lib $WDIR/usr/lib64
ln -s ../bin $WDIR/usr/bin
ln -s ../sbin $WDIR/usr/sbin

# Create necessary device nodes
mknod -m 640 $WDIR/dev/console c 5 1
mknod -m 664 $WDIR/dev/null    c 1 3
cp -a /dev/mapper/control $WDIR/dev/mapper

cp /etc/udev/udev.conf $WDIR/etc/udev/udev.conf

for file in $(find /etc/udev/rules.d/ -type f) ; do
    cp $file $WDIR/etc/udev/rules.d
done

# Install any firmware present
cp -a /lib/firmware/iwlwifi-6*.ucode $WDIR/lib/firmware/
cp -a /lib/firmware/iwlwifi*7265* $WDIR/lib/firmware/

# Install the init file
install -m0755 $DATADIR/$INITIN $WDIR/init

# Install basic binaries
binfiles="sh cat cp dd killall ls mkdir mknod mount umount sed sleep ln rm uname readlink basename udevadm modprobe blkid switch_root cryptsetup"
for f in $binfiles ; do
    ldd /usr/bin/$f | sed "s/\t//" | cut -d " " -f1 >> $libs
    copy $f bin
done

if [ -f /usr/bin/udevd ]; then
    ldd /usr/bin/udevd | sed "s/\t//" | cut -d " " -f1 >> $libs
    copy /usr/bin/udevd bin
fi

if [ -f /usr/lib/systemd/systemd-udevd ]; then
    ldd /usr/lib/systemd/systemd-udevd | sed "s/\t//" | cut -d " " -f1 >> $libs
    copy /usr/lib/systemd/systemd-udevd bin/udevd
fi

# Install libraries
sort $libs | uniq | grep -v fakeroot | while read library ; do
    if [ "$library" == "linux-vdso.so.1" ] ||
        [ "$library" == "linux-gate.so.1" ]; then
        continue
    fi
    copy $library lib
done

cp -a /usr/lib/udev $WDIR/lib
cp -a /usr/lib/systemd $WDIR/lib

( cd $WDIR ; find . | cpio -o -H newc --quiet | gzip -9 ) > $INITRAMFS_FILE

# Remove the temporary directory and file
rm -rf $WDIR $libs
printf "done.\n"
