#!/bin/bash

tmpdir=/tmp/devnull/color_chooser-`uuidgen -t`
mkdir -p ${tmpdir}
pushd ${tmpdir} >/dev/null 2>&1
cat > color_chooser.c << "EOF"
#include <gtk/gtk.h>


int main(int argc, char** argv) {
    gtk_init(&argc, &argv);
    GtkWidget* dialog = gtk_color_chooser_dialog_new("Color Chooser", NULL);
    gtk_dialog_run(GTK_DIALOG(dialog));
    gtk_widget_destroy(dialog);
    return 0;
}
EOF

gcc `pkg-config --libs --cflags gtk+-3.0` color_chooser.c
./a.out >/dev/null 2>&1
popd >/dev/null 2>&1
rm -rf ${tmpdir}
